<?php
/**
 * @file
 * A CKEditor plugin for inserting embedded content via an external URL.
 */

/**
 * Implements hook_ckeditor_plugins().
 */
function oembed_ckeditor_plugins() {
  $path = backdrop_get_path('module', 'oembed') . '/js/oembed';

  $plugins['oembed'] = array(
    'path' => $path,
    'file' => 'plugin.js',
    'buttons' => array(
      'oembed' => array(
        'label' => t('oEmbed'),
        'image' => $path . '/icons/oembed.png',
        'required_html' => array(
          array(
            'tags' => array('iframe'),
          ),
          array(
            'tags' => array('div'),
          ),
        ),
      ),
    ),
  );

  return $plugins;
}

